from tkinter import Label, Button, Text, Tk, Frame, RIGHT, YES, X
root = Tk()
root.title("Criptografador Cifra de Cesar")
root.config(padx=50, pady=100)
root.geometry("900x500")
frame_entrada = Frame(root, width=600, highlightbackground="red", highlightcolor="red", highlightthickness=5, height=200)
frame_entrada.pack()
frame_entrada.propagate(False)
entrada_texto = Text(frame_entrada, width=60, height=8)
entrada_texto.grid(row=2, column=1, columnspan=2, rowspan=2)
botao_cripto = Button(frame_entrada, width=25, height=3, text="Clique aqui para criptografar")
botao_cripto.grid(row=8, column=0, columnspan=2, rowspan=2)
botao_descripto = Button(frame_entrada, width=25, height=3, text="Clique aqui para descriptografar")
botao_descripto.grid(row=8, column=2, columnspan=2, rowspan=2)
frame_saida = Frame(root, width=600, highlightbackground="green", highlightcolor="green", highlightthickness=5, height=200)
frame_saida.pack()
frame_saida.propagate(False)
root.mainloop()